export default [
    {
        id: 1,
        title: 'Double Eagle',
        history: "The Double Eagle was first minted in 1849 during the California Gold Rush. This $20 gold coin symbolized the wealth and prosperity of the United States during the 19th and early 20th centuries. Due to the Gold Recall Order of 1933, most Double Eagles were melted down, making surviving specimens highly sought after by collectors.",
        approximateValue: "$2000",
        yearOfIssue: '1849',
        country: 'United States',
        material: 'Gold',
        rarity: 'Rare',
        image: require('../assets/images/coinImages/coin1.png'),
    },
    {
        id: 2,
        title: '1804 Silver Dollar',
        history: "The 1804 Silver Dollar is known as the \"King of American Coins.\" Despite the date on the coin, it was actually minted much later for diplomatic purposes. Only 15 specimens are known to exist, making it one of the rarest and most valuable coins in the world.",
        approximateValue: "$3 million",
        yearOfIssue: '1804',
        country: 'United States',
        material: 'Silver',
        rarity: 'Extremely Rare',
        image: require('../assets/images/coinImages/coin2.png'),
    },
    {
        id: 3,
        title: '1913 Liberty Head Nickel',
        history: "The 1913 Liberty Head Nickel is shrouded in mystery and controversy. Five known specimens were illegally minted and have fascinating stories behind their creation. These coins have fetched millions at auctions, making them some of the most valuable and coveted coins in numismatics.",
        approximateValue: "$4.5 million",
        yearOfIssue: '1913',
        country: 'United States',
        material: 'Copper-Nickel Alloy',
        rarity: 'Unique',
        image: require('../assets/images/coinImages/coin3.png'),
    },
    {
        id: 4,
        title: '1794 Flowing Hair Dollar',
        history: "The 1794 Flowing Hair Dollar was the first silver dollar struck by the United States Mint. It features a portrait of Lady Liberty with flowing hair. Only a few hundred specimens are known to exist, making it highly desirable among collectors.",
        approximateValue: "$10 million",
        yearOfIssue: '1794',
        country: 'United States',
        material: 'Silver',
        rarity: 'Rare',
        image: require('../assets/images/coinImages/coin4.png'),
    },
    {
        id: 5,
        title: '1943 Copper Penny',
        history: "The 1943 Copper Penny is a rare error coin from the World War II era. Due to the wartime shortage of copper, these pennies were mistakenly struck on copper planchets instead of zinc-coated steel. Only a few are known to exist, making them valuable collectibles.",
        approximateValue: "$100,000+",
        yearOfIssue: '1955',
        country: 'United States',
        material: 'Copper',
        rarity: 'Rare',
        image: require('../assets/images/coinImages/coin5.png'),
    },
    {
        id: 6,
        title: '1982 No Mint Mark Roosevelt Dime',
        history: "Some 1982 Roosevelt Dimes were minted without a mint mark, making them a rare and valuable error coin for collectors.",
        approximateValue: "$50+",
        yearOfIssue: '1982',
        country: 'United States',
        material: 'Copper-Nickel Alloy',
        rarity: 'Rare',
        image: require('../assets/images/coinImages/coin6.png'),
    },
    {
        id: 7,
        title: '1937-D 3-Legged Buffalo Nickel',
        history: "The 1937-D Buffalo Nickel features a buffalo with three legs due to heavy die polishing that removed one of the legs, creating a distinctive and collectible error.",
        approximateValue: "$500+",
        yearOfIssue: '1937',
        country: 'United States',
        material: 'Copper-Nickel Alloy',
        rarity: 'Rare',
        image: require('../assets/images/coinImages/coin7.png'),
    },
    {
        id: 8,
        title: '1984 Double Ear Lincoln Cent',
        history: "The 1984 Lincoln Cent shows doubling on Lincoln's ear, a result of a double die error during the minting process, making it a valuable and unique collectible.",
        approximateValue: "$200+",
        yearOfIssue: '1984',
        country: 'United States',
        material: 'Copper',
        rarity: 'Rare',
        image: require('../assets/images/coinImages/coin8.png'),
    },
]